Via issues preview UI
bignerdranch/Github-Issues-Reader pull request #6
Opened 2022-11-08 21:19 UTC by via-codes

Added State status logic 
Took out all storyboard references and made it exclusively programmatic with the one nib file
Created a NavController 
Issue title bold and single line and Truncate text
Issue User subtext
Person SF symbol added next to username
Issue state green when "open" red when "closed" and displayed all on the same subtext like as user.

2022-11-08 21:30 UTC, kevinrandrup commented on Github Issue Reader/Views/IssuesCollectionVC.swift
> +    func title(){
Lil space here

2022-11-08 21:30 UTC, kevinrandrup commented on IssuePreviewCVCell.swift
> +        if issue.state == .open {
Would you please use a `switch` statement instead?

2022-11-08 21:30 UTC, kevinrandrup commented on IssuePreviewCVCell.swift
> +        issueStatus.configuration?.baseBackgroundColor = .green
This property immediately gets changed below so doesn't do anything here

2022-11-08 21:30 UTC, kevinrandrup commented on IssuePreviewView.swift
> +//    class func nib() -> IssuePreviewView {
We don't need this file anymore, right?

2022-11-08 21:47 UTC, via-codes commented on IssuePreviewCVCell.swift
> +        issueStatus.configuration?.baseBackgroundColor = .green
Whoops. Def was suppose to delete that.

2022-11-08 21:48 UTC, via-codes commented on IssuePreviewView.swift
> +//    class func nib() -> IssuePreviewView {
Correct! I totally didn't realize that we could nix it altogether. Shall I do that?

2022-11-08 21:51 UTC, markd2 reviewed
wow, looks pretty spif!

2022-11-08 21:51 UTC, markd2 commented on Github Issue Reader/ViewController.swift
> +//                print(issue.title)
I try not to check in caveman debugging or development printage.  (And also try not to check in commented-out swaths of code)

2022-11-08 21:51 UTC, markd2 commented on Github Issue Reader/Views/IssuesCollectionVC.swift
> +        return CGSize(width: fullWidth, height: 100)
you can make a constant for the height  (e.g. `let cellHeight: CGFloat = 100`) - that'll make it easier for someone later on to change (this really should be EIGHTY SEVEN POINTS AND NO MORE!!1!!), and if anything else needs to be 100 points tall to match the cell height

2022-11-08 21:51 UTC, markd2 commented on IssuePreviewCVCell.swift
> +    var issueTitle: UILabel = {
common nomenclature for UI components is including the type in the name, like `issueTitleLabel`.  `issueTitle` kind of sounds stringy, like this is the issue title, not the thing that is displaying the issue title.  (and this applies to things up and down here)

2022-11-08 21:51 UTC, markd2 commented on IssuePreviewCVCell.swift
> +    let userPic = UIImageView (image: UIImage(systemName: "person.circle"))
nit: can lose the space before the `(`

2022-11-08 21:51 UTC, markd2 commented on IssuePreviewCVCell.swift
> +        // Create a view to use as a spacer which expands to fill available area
oooh, I'm totally stealing this

2022-11-08 22:10 UTC, kevinrandrup commented on IssuePreviewView.swift
> +//    class func nib() -> IssuePreviewView {
Yeet it

2022-11-10 15:45 UTC, kevinrandrup requested changes
Missing the first AC in #2

> Large title "Issue" that moves into the navigation bar when scrolling. This functionality is built into UINavigationController.

2022-11-10 15:45 UTC, kevinrandrup commented on Github Issue Reader/ViewController.swift
> +            layout.itemSize = UICollectionViewFlowLayout.automaticSize
We manually calculate the height and width of the cell so this doesn't need to be set

2022-11-10 15:45 UTC, kevinrandrup commented on IssuePreviewView.swift
> +//    class func nib() -> IssuePreviewView {
Followup, this didn't get deleted?

2022-11-10 15:45 UTC, kevinrandrup commented on Github Issue Reader/Views/IssuesCollectionVC.swift
> +    }
This function is never called so it never assigns the title of the `navigationItem` to "Issues". It's also not an override that changes an existing function.

2022-11-10 15:45 UTC, kevinrandrup commented on Github Issue Reader/Views/IssuesCollectionVC.swift
> +        navigationController?.navigationBar.prefersLargeTitles = true
The navigation bar isn't visible, so this doesn't so anything

2022-11-11 18:21 UTC, kevinrandrup approved these changes

2022-11-11 18:21 UTC, merged